db:
  image: mysql:5.7.7
  env_file: production.env
  volumes:
    - '/db/data:/var/lib/mysql'
redis:
  image: redis
  volumes:
    - '/redis/data:/data'
web:
  image: brunobispo/gnib-tracking:latest
  ports:
    - "80:3000"
  env_file: production.env
  environment:
    RAILS_ENV: production
    RAILS_SERVE_STATIC_FILES: true
  links:
    - db
    - redis
worker:
  image: brunobispo/gnib-tracking:latest
  command: bash -c "bin/db-ready && bundle exec sidekiq -e production -c 25"
  env_file: production.env
  environment:
    RAILS_ENV: production
  links:
    - db
    - redis
